import 'package:attendance/src/attendance/domain/entities/bus_route.dart';
import 'package:attendance/src/attendance/domain/entities/school.dart';
import 'package:attendance/src/attendance/domain/entities/student.dart';

final List<School> schoolList = [
  School(
    schoolName: "School 1",
    schoolArea: "School 1 Area",
    busRoutes: [
      BusRoute(
          routeNumber: 1,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
          routeNumber: 2,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 2),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
        routeNumber: 3,
        schoolName: "schoolName",
        area: "area",
        students: [
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
        ],
      ),
    ],
  ),
  School(
    schoolName: "School 2",
    schoolArea: "School 1 Area",
    busRoutes: [
      BusRoute(
          routeNumber: 1,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
          routeNumber: 2,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 2),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
        routeNumber: 3,
        schoolName: "schoolName",
        area: "area",
        students: [
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
        ],
      ),
    ],
  ),
  School(
    schoolName: "School ",
    schoolArea: "School 1 Area",
    busRoutes: [
      BusRoute(
          routeNumber: 1,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID",
                studentName: "studentName",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
          routeNumber: 2,
          schoolName: "schoolName",
          area: "area",
          students: [
            Student(
                studentID: "studentID4",
                studentName: "studentName4",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 2),
            Student(
                studentID: "studentID3",
                studentName: "studentName3",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
            Student(
                studentID: "studentID2",
                studentName: "studentName2",
                grade: 1,
                group: 1,
                phoneNumber: "1",
                fathersNumber: "fathersNumber",
                locationCoordinates: "locationCoordinates",
                makkaniNumber: "makkaniNumber",
                schoolName: "schoolName",
                busRoute: 1),
          ]),
      BusRoute(
        routeNumber: 3,
        schoolName: "schoolName",
        area: "area",
        students: [
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
          Student(
              studentID: "studentID",
              studentName: "studentName",
              grade: 1,
              group: 1,
              phoneNumber: "1",
              fathersNumber: "fathersNumber",
              locationCoordinates: "locationCoordinates",
              makkaniNumber: "makkaniNumber",
              schoolName: "schoolName",
              busRoute: 1),
        ],
      ),
    ],
  ),
];
